/*
 * Copyright 2014 John Ahlroos
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package fi.jasoft.draganddrop.client;

import java.util.Map;

import com.vaadin.client.ComponentConnector;

import fi.jasoft.draganddrop.client.configurations.AbstractDragAndDropConfiguration;

/**
 * Generated by DragAndDropGenerator
 *
 */
public class DragAndDropConfigurationManagerImpl implements
		DragAndDropConfigurationManager {

	@Override
	public Map<String, AbstractDragAndDropConfiguration<? extends ComponentConnector>> getConfigurations() {
		throw new IllegalStateException(
				"This class should be generated with DragAndDropConfigurationsGenerator");

	}
}
