package fi.jasoft.draganddrop.client;

import java.util.Map;

import com.vaadin.client.ComponentConnector;

import fi.jasoft.draganddrop.client.configurations.AbstractDragAndDropConfiguration;

/**
 * Generated by DragAndDropGenerator
 *
 */
public class DragAndDropConfigurationManagerImpl implements DragAndDropConfigurationManager {

	@Override
	public Map<String, AbstractDragAndDropConfiguration<? extends ComponentConnector>> getConfigurations() {
		throw new IllegalStateException("This class should be generated with DragAndDropConfigurationsGenerator");
		
	}
}
